export default {
  "New layer": "Новый слой",
  "Elements on layer {0}": "Элементы слоя {0}",
  "Layers": "Слои",
  "Project config": "Конфигурация проекта",
  "width": "ширина",
  "height": "высота",
  "Cancel": "Отмена",
  "Save": "Сохранить",
  "Layer config": "Конфигурация слоя",
  "Name": "Название",
  "opacity": "прозрачность",
  "altitude": "высота",
  "order": "порядок",
  "Delete": "Удалить",
  "New project": "Новый проект",
  "Save project": "Сохранить проект",
  "Load project": "Загрузить проект",
  "3D View": "3D",
  "2D View": "2D",
  "3D First Person": "От первого лица",
  "Zoom in": "Приблизить",
  "Zoom out": "Отдалить",
  "Pan": "Pan",
  "Undo (CTRL-Z)": "Отменить (CTRL-Z)",
  "Configure project": "Configure project",
  "Open catalog": "Открыть каталог",
  "Reset": "Перегрузить",
  "Unselect": "Отменить выделение",
  "Configure layer": "Сконфигурировать слой",
  "Delete layer": "Удалить слой",
  "Properties: [{0}] {1}": "Свойство: [{0}] {1}",
  "Get Screenshot": "Сделать снимок",
  "Catalog": "Каталог",
  "Rotation": "Поворот",
  "Altitude": "Высота",
  "Would you want to start a new Project?": "Не хотите начать новый проект?",
  "Copy": "Копировать",
  "Paste": "Вставить",
  "Search Element": "Найти элемент",
  "Last Selected": "Псоледний выбраный",
  "Length": "Длина",
  "Lines": "Линии",
  "Holes": "Полости",
  "Items": "Элементы",
  "Areas": "Площади",
  "Snap to Point": "Привязать к точке",
  "Snap to Line": "Привязать к линии",
  "Snap to Segment": "Привязать к сегменту",
  "Snap to Grid": "Привязать к матрице",
  "Mouse X Coordinate": "Координата X мышки",
  "Mouse Y Coordinate":"Координата Y мышки",
  "Scene Zoom Level": "Уровень приближения сцены"
}
